### ISSUE TITLE
TODO for dat alpha (first stable version)

### ISSUE THREAD

**Issue by max-mapper** [datproject/dat#29]
most of my work the last 2 months has been on low level stuff, this is a todo list of things that need to get done before I can ship v1
- [x] authentication (https://github.com/maxogden/auth-socket, http basic auth for starters)
- [x] push replication (right now only pull is implemented, waiting on auth)
- [x] CLI commands should fall back to networked protocol if DB is locked (e.g. if a server is running)
- [x] use protobuf for on-disk storage format
- [x] solidify schema semantics - e.g. are sparse objects allowed, should schema be explicit/implicit
- [x] make sure dat installs on windows okay. closed via https://github.com/maxogden/dat/commit/c7ace7f0b297d252c3c8f2aafc773b7d1903d7db
- [x] make sure there's progress feedback on all operations (import, push, pull)
- [x] generic encode/decode API https://github.com/maxogden/dat/issues/85
- [x] blob/attachment storage support
- [x] binary push/pull/clone https://github.com/maxogden/dat/issues/110
- [x] make the dat api (mostly) levelup compatible
- [x] `dat init` should prompt + make a `dat.json` file (@mafintosh is working on this)
- [x] integrate with transformer (data transformations) https://github.com/maxogden/dat/issues/93
- [x] store remotes (@mafintosh)
- [x] basic web GUI with that lets you CRUD (https://github.com/maxogden/dat-editor)
- [x] JS API documentation (https://github.com/maxogden/dat/blob/master/docs/api.md)
- [x] HTTP API documentation
- [x] binary readStream (@mafintosh)
- [x] load backends from dat.json on startup (https://github.com/maxogden/dat/issues/125)
- [x] run listen hook from dat.json (https://github.com/maxogden/dat/issues/125)
- [x] skim blobs (@maxogden)
- [x] stats API (@mafintosh)
- [x] review stream destroy/cleanup
- [x] review error handling
- [x] usage docs and guides (https://github.com/maxogden/dat/issues/132) (@maxogden)
- [x] rewrite readme (@maxogden)
- [x] new website (https://github.com/maxogden/dat-data.com/issues/6) (@maxogden)
- [x] review stdout/stderr output (@maxogden)
- [x] add docs for transformations to js-api (@maxogden)
- [x] gzip replication streams (@mafintosh)
- [x] read existing dat.json during `dat init` (dont delete it) (https://github.com/maxogden/dat/pull/149)
- [x] abtract out skim-blobs into a generic dat-remote-blobs module (@mafintosh)
- [x] decide on how to pass CLI args to dat constructor (https://github.com/maxogden/dat/commit/9e9dd2da84e059ab932a88898676ecb59f7612ac#commitcomment-7419170)
- [x] make a 'deploy dat on heroku' button demo that works with postgres + sqldown (@maxogden)

(I'll check off boxes as I complete them)
